disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - multiple_closures_with_trailing_closure
  - nesting
  - empty_enum_arguments
  - redundant_string_enum_value
  - type_name
  - cyclomatic_complexity  
  - line_length
  - function_body_length   
  - file_length
excluded:
  - Desafio/Resources/Generated/R/R.generated.swift
  - Pods

identifier_name: 4
