# Uncomment the next line to define a global platform for your project
platform :ios, '13.4'

target 'TFilmes' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TFilmes

  pod 'RealmSwift'

  target 'TFilmesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TFilmesUITests' do
    # Pods for testing
  end

end
